blank_issues_enabled: false
contact_links:
  - name: ⚠️ Support boundaries ⚠️
    url: https://atlassian-labs.github.io/data-center-terraform/troubleshooting/SUPPORT_BOUNDARIES/
    about: Please read the scope of support before raising an issue
  - name: Infrastructure installation feedback and questions
    url: http://bit.ly/dcapt_slack
    about: In case of technical questions, issues or problems using this project with DC Apps Performance Toolkit, contact us for support in the community Slack `#data-center-app-performance-toolkit` channel.
