name: Report an issue
description: Do you have experienced any problem with deployment Atlassian products on Kubernetes?
title: "[Issue] - "
labels: [issue, triage]
body:
  - type: markdown
    attributes:
      value: |
        ## 💡 Report issues only 💡
        
        Thanks for taking the time to report an issue! Before reporting the problem, please read [Supported Boundaries document](https://github.com/atlassian-labs/data-center-terraform/troubleshooting/SUPPORT_BOUNDARIES/) and [Troubleshooting](https://atlassian-labs.github.io/data-center-terraform/troubleshooting/TROUBLESHOOTING/) page.
  - type: textarea
    id: issue-description
    attributes:
      label: Issue
      description: Describe your problem, including the use case and details of the issue
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Product
      description: You can select multiple products
      options:
        - Bamboo
      multiple: true
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/atlassian-labs/data-center-terraform/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
