name: Add SSH keys
on:
  push:
    branches:
      - main
    paths-ignore: # https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#example-ignoring-paths
      - 'docs/**'
      - '.atlassian/**'
      - 'test/unittest**'
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: Add SSH keys
    runs-on: ubuntu-latest
    env:
      PUBLIC_KEY: ${{secrets.BITBUCKET_E2E_TEST_PUB_SSH_KEY}}

    steps:
      - name: Add private SSH key for Bitbucket tests
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.BITBUCKET_E2E_TEST_SSH_KEY }}
          name: bitbucket-e2e # optional
          known_hosts: "not-needed"
          if_key_exists: fail # replace / ignore / fail; optional (defaults to fail)

      - name: Add public SSH key for Bitbucket tests
        run: |
          echo $PUBLIC_KEY >> /home/runner/.ssh/bitbucket-e2e.pub

      - name: List contents of .ssh folder
        run: |
          ls -lrtra /home/runner/.ssh

      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Go environment
        uses: actions/setup-go@v2.1.4
        with:
          # The Go version to download (if necessary) and use. Supports semver spec and ranges.
          go-version: 1.17
      - name: Setup dependencies
        working-directory: test/
        run: go get -v -t -d ./... && go mod tidy

      - name: Test key push
        id: key-push
        working-directory: test/
        run: go test ./e2etest -run TestSshPush -v