name: Documentation - Deploy to gh-pages
on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install mkdocs requirements
        run: pip install -r requirements.txt
        working-directory: docs
      - name: Publish documentation to gh-pages branch
        run: mkdocs gh-deploy --force
        working-directory: docs
