name: E2E Testing with no domain
on:
  schedule:
    - cron: '0 1 */2 * *' # schedule the test to run every second day at 1:00am
  push:
    branches:
      - main
    paths-ignore: # https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#example-ignoring-paths
      - 'docs/**'
      - '.atlassian/**'
      - 'test/unittest**'
  pull_request_target:
    types: [ labeled ]
  workflow_dispatch:

jobs:
  test:
    if: ${{ github.event.label.name == 'e2e' || github.event_name == 'push' || github.event_name == 'workflow_dispatch' || github.event_name == 'schedule' }}
    name: E2E Testing with no domain
    runs-on: ubuntu-latest
    env:
      AWS_DEFAULT_REGION: us-east-1
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_VAR_bamboo_license: ${{ secrets.TF_VAR_BAMBOO_LICENSE }}
      TF_VAR_confluence_license: ${{ secrets.TF_VAR_CONFLUENCE_LICENSE }}
      TF_VAR_bitbucket_license: ${{ secrets.TF_VAR_BITBUCKET_LICENSE }}
      TF_VAR_bamboo_admin_password: ${{ secrets.TF_VAR_BAMBOO_ADMIN_PASSWORD }}
      TF_VAR_bitbucket_admin_password: ${{ secrets.TF_VAR_BITBUCKET_ADMIN_PASSWORD }}
      USE_DOMAIN: "false"

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Pin Kubectl version
        uses: azure/setup-kubectl@v2.0
        with:
          version: 'v1.24.0'

      - name: Setup Go environment
        uses: actions/setup-go@v3
        with:
          go-version: '1.18'

      - name: Setup dependencies
        id: setup-dependencies
        working-directory: test/
        run: |
          go version
          go get -v -t -d ./... && go mod tidy
          echo ::set-output name=exit_code::$?

      - name: Create test output directory
        run: mkdir test/e2etest/artifacts

      - name: Add private SSH key for Bitbucket tests
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.BITBUCKET_E2E_TEST_PRIV_SSH_KEY }}
          name: bitbucket-e2e # optional
          known_hosts: dummy-entry
          if_key_exists: fail # replace / ignore / fail; optional (defaults to fail)

      - name: Add public SSH key for Bitbucket tests
        run: |
          echo ${{ secrets.BITBUCKET_E2E_TEST_PUB_SSH_KEY }} > /home/runner/.ssh/bitbucket-e2e.pub

      - name: E2E Testing with no domain
        id: e2e-test
        working-directory: test/
        run: |
          set -o pipefail
          go test ./e2etest -v -timeout 85m -run Installer | tee ./e2etest/artifacts/e2etest.log

      - name: Upload test log files
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: e2e-test-artifacts
          path: test/e2etest/artifacts/
