name: Unit Testing
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'modules/**'
      - 'test/**'
  pull_request:

jobs:
  test:
    name: Automated Testing
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Setup Go environment
        uses: actions/setup-go@v3
        with:
          go-version: '1.18'

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
          args: --timeout 3m0s
          working-directory: test/
          # Optional: if set to true then the action will use pre-installed Go.
          skip-go-installation: true
      - name: Setup dependencies
        working-directory: test/
        run: go get -v -t -d ./... && go mod tidy
      - name: Unit tests
        working-directory: test/
        run: go test ./unittest/... -v