INSTALLER_HELP="""This script provisions the infrastructure for Atlassian Data Center products in AWS environment.
The infrastructure will be generated by terraform and state of the resources will be kept in a S3 bucket which will be provision by this script if is not existed.

Before installing the infrastructure make sure you have completed the configuration process and did all perquisites.
For more information visit https://github.com/atlassian-labs/data-center-terraform.
"""

UNINSTALLER_HELP="""** WARNING **

This script destroys the infrastructure for Atlassian Data Center products in AWS environment. You may lose all application data.

The infrastructure will be removed by terraform. Also the terraform state could be removed if you use switch `-t` in uninstall command."""