from typing import Optional
from python_terraform import *
from config import Config

import typer

HELP_TEXT = """This script provisions the infrastructure for Atlassian Data Center products in AWS environment.
The infrastructure will be generated by terraform and state of the resources will be kept in a S3 bucket which will be provision by this script if is not existed.

Before installing the infrastructure make sure you have completed the configuration process and did all perquisites.
For more information visit https://github.com/atlassian-labs/data-center-terraform."""

app = typer.Typer(add_completion=False, help=HELP_TEXT)


@app.command()
def install(
    config: Optional[str] = typer.Option(
        "config.tfvars", help="Terraform configuration file."
    ),
    force: bool = False,
):
    config = Config(config)
    print(config.get_products())


@app.command()
def uninstall(config: Optional[str] = "config.tfvars", force: bool = False):
    config = Config(config)
    print(config.get_products())

    # tf = Terraform(working_dir='.')
    # print("------------")
    # print(tf.output())


def configure_logging():
    FORMAT = "%(levelname)s - %(asctime)s (%(name)s) %(message)s"
    logging.basicConfig(level=os.environ.get("LOGLEVEL", "INFO"), format=FORMAT)


if __name__ == "__main__":
    configure_logging()
    app()
